# Generated by Django 4.2.10 on 2024-04-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_birth_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
