# Generated by Django 4.2.10 on 2024-06-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
