# Generated by Django 4.2.10 on 2024-06-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecordimage',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='healthrecordimage',
            name='title',
        ),
        migrations.DeleteModel(
            name='HealthRecordFolder',
        ),
    ]
