# Generated by Django 4.2.10 on 2024-04-03 03:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('chat_history', models.JSONField(blank=True, default=list)),
                ('summarized_chat_history', models.JSONField(blank=True, default=list)),
                ('last_entered', models.DateTimeField(auto_now=True)),
                ('entered', models.BooleanField(default=False)),
                ('leaved', models.BooleanField(default=True)),
            ],
        ),
    ]
