# Generated by Django 4.2.10 on 2024-06-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
