# Generated by Django 4.2.10 on 2024-05-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_records', '0001_initial'),
        ('chat_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='health_records',
            field=models.ManyToManyField(related_name='chatrooms', to='health_records.healthrecordimage'),
        ),
    ]
