# Generated by Django 4.2.10 on 2024-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_services", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="chat_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="summarized_chat_history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
