# Generated by Django 4.2.10 on 2024-02-12 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_services", "0002_chatroom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatroom",
            old_name="recent_chat_history",
            new_name="chat_history",
        ),
    ]
