# Generated by Django 4.2.10 on 2024-02-22 09:29

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chat_services", "0003_alter_chatroom_chat_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="last_activity",
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
