# Generated by Django 4.2.10 on 2024-05-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_services', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempChatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom_id', models.CharField(max_length=255, unique=True)),
                ('chat_num', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp_images/')),
                ('ocr_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
