# Generated by Django 4.2.10 on 2024-06-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_services', '0004_alter_chatroom_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='title',
            field=models.CharField(default='AI 분석되지 않은 이미지입니다', max_length=255),
        ),
    ]
