# Generated by Django 4.2.10 on 2024-05-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_services', '0004_tempchatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempchatroom',
            name='ocr_text',
        ),
    ]
